spring:
  #数据库连接
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://218.28.133.52:7111/rjcloud_db?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: HOLIDAY{GWeo7RCM+57lLPcq+xH5GKt3u50bjRVv4YnuiB8OvRkSuYtLwko6fhgv8t6yQ1vrV2tHwJUhTUciaQeh69otMVVyrnQOoKdjq+Gw05GSq8F0sYrotkrL0SYFV/0DLScCtf077ApcvsexaI3sH/0TLhANx/xdx2WqhsLAxzqRev6nxDmf42vX3/sKCRzfjhMvoBJTRWOJ/LVtDnTta12jeZd0w6aX+Ue7cI/iQwHxHt4YeXxqHZiX9YEmESjkywfQLcF0VLFH0o214MmiUEAAyKk4BkoES6gj7eLRwK6PYFxxShr6eaYat6ejU8ZfaalXQOnTMEYRq3kg55OMHsR3Ow==}
    password: HOLIDAY{C/tLBv8CxJPGH7Q6QpSczFoHWbZn3f1uhQ7M83YscqG9wClREUJyA/qnr1BiLlBurjx95L7VsgSc8nRaLeYyy5yEnK6I/IrNEgYqYL511HWa8zdEY4jD/btWNAvp43VuSfPcAKfvnEbUhvc0ft+O8AmDANosOS2VuUqjDq6FKFHa+kXyEp5WqQrEEOzYkg8s7OynDjRIz9ZEjlykxNqx5DhViS4k3xGwH77cJ37quqWzBxc1J9r7vCTH1f45m8tc8n1IKEZfJULDpvB+/riqPdWl0l+p6uVdvY1oU3Ezyyb5yzJ/mWZBcXdr2r4LorUGTIES/hMIavz9MERqNtVq4A==}
    druid:
      # 初始连接数
      initialSize: 5
      # 最小连接池数量
      minIdle: 10
      # 最大连接池数量
      maxActive: 20
      # 配置获取连接等待超时的时间
      maxWait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      # 配置一个连接在池中最大生存的时间，单位是毫秒
      maxEvictableIdleTimeMillis: 900000
      # 配置检测连接是否有效
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      webStatFilter:
        enabled: true
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*,/swagger/*"
      statViewServlet:
        enabled: true
        # 设置白名单，不填则允许所有访问
        allow:
        url-pattern: /druid/*
        # 控制台管理用户名和密码
        login-username: admin
        login-password: 123456
      filter:
        stat:
          enabled: true
          # 慢SQL记录
          log-slow-sql: true
          slow-sql-millis: 1000
          merge-sql: true
        wall:
          config:
            multi-statement-allow: true
  #redis
  redis:
    host: 218.28.133.52
    #    password: 123456
    port: 7113
    timeout: 5000
    lettuce:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 20
        min-idle: 0
  servlet:
    multipart:
      resolve-lazily: true
      max-file-size: 50MB
      max-request-size: 50MB
  #rabbitmq
  rabbitmq:
    host: 218.28.133.52
    port: 9976
    virtual-host: johnyehyo
    username: HOLIDAY{LUm/LnezDowQ2rNFG9d+QLH9NVFe2K2HnQ7xNTJlNFqfT4oWzxgsqVQTi0MU42CsJZ6ND8oXFVyHFypRVWpx0rngGc6aLa2pRk1uH1d0q4zQri9WY2kTKeJIhYQDW7COsNgbTI8ECYe8EV1MTMDUCdt0iOnnq2sOZkYFs71LkwuatTnYVcunYifl2IBN/YjKvWDT4NEm7BNIunCDJMg4MAPe8SesM5rut3TDkbEjmLcVItFyzv5ptS5Iovq/qQdQX4bCFh4EELuWY0JGgMuM/5S9TvWKQCj0tjpl0MgGYuuauNZVFA/0h48d8ncSiIDT09lFUYxgt2cEUnhpajacDA==}
    password: HOLIDAY{Ige2MnJ0iTCQnBJ2GtA/RzAhaLBOo/Ga6aw3a8r2FOzEJSRYtDGTt5eKPPzi2OTv0jzaehI8ovKR/VlOW1gbEnb3URgBVi9mRpxjSqufcrAmvpJsOERDgIS5tuE6j92T6AZWNzm1Q//pCtDCzwOD5Dm5Al9N9IYIafQ8QOXtLZanel4I/b+J8Q12Z7UdHAIAnVT/myMbHHQ9RMVfxV0VDJVLZfAFFG/axZukl/Q9H1yrPCMN/hz2STZIkQLHU+VFCGqBlOByk3JKytyExWpdy63+04s5BnqRyniFUpkS2VlFWcWTTkYQJZo9sedizV1Y6i4i1n+QGIncUYPQTv+kXA==}
    publisher-confirm-type: correlated
    publisher-returns: true
    listener:
      simple:
        acknowledge-mode: manual
        retry:
          enabled: false
#          max-attempts: 5
#          # 重试最大间隔时间
#          max-interval: 10000
#          # 重试初始间隔时间
#          initial-interval: 2000
#          # 间隔时间乘子，间隔时间*乘子=下一次的间隔时间，最大不能超过设置的最大间隔时间
#          multiplier: 2
    template:
      mandatory: true

server:
  tomcat:
    max-swallow-size: -1

#文件存储路径
file:
  path: D:\other\file
  avator: /avator
  download: /download
  upload: /upload
  # 文件大小 /M
  maxSize: 100
  avatarMaxSize: 5
  localUrl: http://127.0.0.1:8088
# swagger开关
swagger:
  enable: true

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

xxl:
  job:
    admin:
      #### 调度中心部署跟地址 [选填]：如调度中心集群部署存在多个地址则用逗号分隔。执行器将会使用该地址进行"执行器心跳注册"和"任务结果回调"；为空则关闭自动注册；
      addresses: http://127.0.0.1:8080/xxl-job-admin
      ### 执行器通讯TOKEN [选填]：非空时启用
    accessToken: 9A3CFFD2113813559663B1D1612FBE2E
    ### 执行器AppName [选填]：执行器心跳注册分组依据；为空则关闭自动注册
    executor:
      appname: basic-framework
      ### 执行器注册 [选填]：优先使用该配置作为注册地址，为空时使用内嵌服务 ”IP:PORT“ 作为注册地址。从而更灵活的支持容器类型执行器动态IP和动态映射端口问题。
      address:
      ### 执行器IP [选填]：默认为空表示自动获取IP，多网卡时可手动设置指定IP，该IP不会绑定Host仅作为通讯实用；地址信息用于 "执行器注册" 和 "调度中心请求并触发任务"；
      ip:
      ### 执行器端口号 [选填]：小于等于0则自动获取；默认端口为9999，单机部署多个执行器时，注意要配置不同执行器端口
      port: 9999
      ### 执行器运行日志文件存储磁盘路径 [选填] ：需要对该路径拥有读写权限；为空则使用默认路径；
      logpath: ../xxl-job/jobhandler
      ### 执行器日志文件保存天数 [选填] ： 过期日志自动清理, 限制值大于等于3时生效; 否则, 如-1, 关闭自动清理功能；
      logretentiondays: 30