server:
  port: 8288
  tomcat:
    max-connections: 500
    threads:
      max: 1000
    #最大等待数
    accept-count: 200
  servlet:
    context-path: /base

spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  main:
    allow-circular-references: true
  application:
    name: rjsoft
  profiles:
    active: druid
  #jackson配置
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
    default-property-inclusion: ALWAYS
  #上传配置
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 100MB
  cloud:
    sentinel:
      transport:
        dashboard: localhost:8859

#mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# token配置
token:
  # 令牌自定义标识
  header: Authorization
  # 令牌密钥
  secret: abcdefghijklmnopqrstuvwxyz
  # 令牌有效期（默认30分钟）
  expireTime: 30
  # SSO token (单位秒)
  sso:
    expireTime: 30

JohnYehyo:
  version: 1.0.0
  # 验证码类型 math 数组计算 char 字符验证
  captchaType: math
  # 加密公钥
  key: 113813559663B1D1
  # 密码使用时长限制(天)
  pwd_time: 30
  # 历史密码记录数
  pwd_history: 2

jasypt:
  encryptor:
    password: JohnYehyo
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator

# 防止XSS攻击
xss:
  # 过滤开关
  enabled: true
  # 排除链接（多个用逗号分隔）
  excludes: /agent/*
  # 匹配链接（多个用逗号分隔）
  urlPatterns: /*