version: '3.3'
services:
  zookeeper:
  image: wurstmeister/zookeeper
  ports:
    - 2181:2181
  container_name: zookeeper
  networks:
    default:
      ipv4_address: 172.18.0.2
  kafka0:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    container_name: kafka0
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka0:9092
      KAFKA_LISTENERS: PLAINTEXT://kafka0:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 0
    volumes:
      - /data/kafka/data/kafka0/data:/data
      - /data/kafka/data/kafka0/log:/datalog
    networks:
      default:
        ipv4_address: 172.18.0.3
  kafka1:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    container_name: kafka1
    ports:
      - 9093:9093
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9093
      KAFKA_LISTENERS: PLAINTEXT://kafka1:9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
    volumes:
      - /data/kafka/data/kafka1/data:/data
      - /data/kafka/data/kafka1/log:/datalog
    networks:
      default:
        ipv4_address: 172.18.0.4
  kafka2:
    image: wurstmeister/kafka
    depends_on:
      - zookeeper
    container_name: kafka2
    ports:
      - 9094:9094
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9094
      KAFKA_LISTENERS: PLAINTEXT://kafka2:9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
    volumes:
      - /data/kafka/data/kafka2/data:/data
      - /data/kafka/data/kafka2/log:/datalog
    networks:
      default:
        ipv4_address: 172.18.0.5
networks:
  default:
    external:
      name: zookeeper_kafka